remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "AutoGluon 1.0: AutoML at Your Fingertips"
description: "NeurIPS 2023,  New Orleans Convention Center, 2:00pm CST December 10th, Room 214."
